const YOUNG_TYPE = 1;
const PARENT_TYPE = 2;

const QUESTIONNARIE_52 = 52;
const QUESTIONNARIE_27 = 27;
const QUESTIONNARIE_10 = 10;

export {
  YOUNG_TYPE,
  PARENT_TYPE,
  QUESTIONNARIE_10,
  QUESTIONNARIE_27,
  QUESTIONNARIE_52,
};
